//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Please do not modify by hand
//==============================================================================

// Keeps format for the parser
// ignore_for_file: always_use_package_imports, lines_longer_than_80_chars

import 'package:language_helper/language_helper.dart';

import 'data/ar.dart';
import 'data/de.dart';
import 'data/en.dart';
import 'data/es.dart';
import 'data/fr.dart';
import 'data/hi.dart';
import 'data/id.dart';
import 'data/it.dart';
import 'data/ja.dart';
import 'data/ko.dart';
import 'data/pt.dart';
import 'data/ru.dart';
import 'data/tr.dart';
import 'data/vi.dart';
import 'data/zh.dart';
import 'data/zh_TW.dart';

final LazyLanguageData languageData = {
  LanguageCodes.ar: () => arLanguageData,
  LanguageCodes.de: () => deLanguageData,
  LanguageCodes.en: () => enLanguageData,
  LanguageCodes.es: () => esLanguageData,
  LanguageCodes.fr: () => frLanguageData,
  LanguageCodes.hi: () => hiLanguageData,
  LanguageCodes.id: () => idLanguageData,
  LanguageCodes.it: () => itLanguageData,
  LanguageCodes.ja: () => jaLanguageData,
  LanguageCodes.ko: () => koLanguageData,
  LanguageCodes.pt: () => ptLanguageData,
  LanguageCodes.ru: () => ruLanguageData,
  LanguageCodes.tr: () => trLanguageData,
  LanguageCodes.vi: () => viLanguageData,
  LanguageCodes.zh: () => zhLanguageData,
  LanguageCodes.zh_TW: () => zhTWLanguageData,
};
