//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

import 'package:language_helper/language_helper.dart';

const arLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "لا توجد تغييرات للحفظ",
  "@{count} translation@{plural} saved successfully": LanguageConditions(
    param: 'count',
    conditions: {
      '0': 'تم حفظ 0 ترجمة بنجاح',
      '1': 'تم حفظ ترجمة واحدة بنجاح',
      '2': 'تم حفظ ترجمتين بنجاح',
      '_': 'تم حفظ @{count} ترجمة بنجاح',
    },
  ),
  "Changes discarded": "تم تجاهل التغييرات",
  "Language Improver": "محسّن اللغة",
  "No languages available": "لا توجد لغات متاحة",
  "No translations found": "لم يتم العثور على ترجمات",
  "Cancel": "إلغاء",
  "Save": "حفظ",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "المفتاح:",
  "Default": "افتراضي",
  "with Condition": "مع شرط",
  "Param: @{param}": "المعامل: @{param}",
  "Target": "الهدف",
  "Convert to Condition": "تحويل إلى شرط",
  "Convert to String": "تحويل إلى نص",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "إضافة شرط",
  "Enter condition key:": "أدخل مفتاح الشرط:",
  "e.g., 0, 1, _ or default": "مثال: 0، 1، _ أو افتراضي",
  "Common keys: 0, 1, 2, _ (default)": "المفاتيح الشائعة: 0، 1، 2، _ (افتراضي)",
  "Condition key cannot be empty": "مفتاح الشرط لا يمكن أن يكون فارغاً",
  "Condition key \"@{key}\" already exists":
      "مفتاح الشرط \"@{key}\" موجود بالفعل",
  "Add": "إضافة",
  "Parameter name cannot be empty": "اسم المعامل لا يمكن أن يكون فارغاً",
  "At least one condition is required": "يُطلب شرط واحد على الأقل",
  "Condition \"@{key}\" cannot be empty":
      "الشرط \"@{key}\" لا يمكن أن يكون فارغاً",
  "Edit Condition": "تعديل الشرط",
  "Reference (Default Language)": "المرجع (اللغة الافتراضية)",
  "Parameter: @{param}": "المعامل: @{param}",
  "Conditions:": "الشروط:",
  "Parameter Name": "اسم المعامل",
  "e.g., count, hours, number": "مثال: عدد، ساعات، رقم",
  "The parameter used in the translation text":
      "المعامل المستخدم في نص الترجمة",
  "Conditions": "الشروط",
  "No conditions. Add one to get started.": "لا توجد شروط. أضف واحداً للبدء.",
  "DEFAULT": "افتراضي",
  "Remove Condition": "إزالة الشرط",
  "Translation Value": "قيمة الترجمة",
  "Enter translation for this condition": "أدخل الترجمة لهذا الشرط",
  "Used when no other condition matches": "يُستخدم عندما لا يتطابق أي شرط آخر",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "اللغة الافتراضية",
  "Target Language": "اللغة المستهدفة",
  "Search translations...": "البحث في الترجمات...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": "@{count} حرف",
  "Show less": "عرض أقل",
  "Show more": "عرض المزيد",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "أدخل اسم المعامل الذي سيُستخدم في الترجمة:",
  "e.g., count, number, hours": "مثال: عدد، رقم، ساعات",
  "This parameter will be used in conditions":
      "سيتم استخدام هذا المعامل في الشروط",
  "Current value:": "القيمة الحالية:",
  "This will become the default condition (_)": "سيصبح هذا الشرط الافتراضي (_)",
  "Converted to Condition successfully": "تم التحويل إلى شرط بنجاح",
  "Continue": "متابعة",
  "No valid condition value found": "لم يتم العثور على قيمة شرط صالحة",
  "Select which condition value to use as the string:":
      "اختر قيمة الشرط التي ستُستخدم كنص:",
  "Converted to String using condition \"@{key}\"":
      "تم التحويل إلى نص باستخدام الشرط \"@{key}\"",
  "Convert": "تحويل",
  "Condition updated": "تم تحديث الشرط",
};
