//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

import 'package:language_helper/language_helper.dart';

const deLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "Keine Änderungen zu speichern",
  "@{count} translation@{plural} saved successfully": LanguageConditions(
    param: 'count',
    conditions: {
      '0': '0 Übersetzungen erfolgreich gespeichert',
      '1': '1 Übersetzung erfolgreich gespeichert',
      '_': '@{count} Übersetzungen erfolgreich gespeichert',
    },
  ),
  "Changes discarded": "Änderungen verworfen",
  "Language Improver": "Sprachverbesserer",
  "No languages available": "Keine Sprachen verfügbar",
  "No translations found": "Keine Übersetzungen gefunden",
  "Cancel": "Abbrechen",
  "Save": "Speichern",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "Schlüssel:",
  "Default": "Standard",
  "with Condition": "mit Bedingung",
  "Param: @{param}": "Param: @{param}",
  "Target": "Ziel",
  "Convert to Condition": "In Bedingung umwandeln",
  "Convert to String": "In Zeichenkette umwandeln",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "Bedingung hinzufügen",
  "Enter condition key:": "Bedingungsschlüssel eingeben:",
  "e.g., 0, 1, _ or default": "z. B. 0, 1, _ oder Standard",
  "Common keys: 0, 1, 2, _ (default)":
      "Häufige Schlüssel: 0, 1, 2, _ (Standard)",
  "Condition key cannot be empty": "Bedingungsschlüssel darf nicht leer sein",
  "Condition key \"@{key}\" already exists":
      "Bedingungsschlüssel \"@{key}\" existiert bereits",
  "Add": "Hinzufügen",
  "Parameter name cannot be empty": "Parametername darf nicht leer sein",
  "At least one condition is required":
      "Mindestens eine Bedingung ist erforderlich",
  "Condition \"@{key}\" cannot be empty":
      "Bedingung \"@{key}\" darf nicht leer sein",
  "Edit Condition": "Bedingung bearbeiten",
  "Reference (Default Language)": "Referenz (Standardsprache)",
  "Parameter: @{param}": "Parameter: @{param}",
  "Conditions:": "Bedingungen:",
  "Parameter Name": "Parametername",
  "e.g., count, hours, number": "z. B. Anzahl, Stunden, Zahl",
  "The parameter used in the translation text":
      "Der in der Übersetzung verwendete Parameter",
  "Conditions": "Bedingungen",
  "No conditions. Add one to get started.":
      "Keine Bedingungen. Fügen Sie eine hinzu, um zu beginnen.",
  "DEFAULT": "STANDARD",
  "Remove Condition": "Bedingung entfernen",
  "Translation Value": "Übersetzungswert",
  "Enter translation for this condition":
      "Übersetzung für diese Bedingung eingeben",
  "Used when no other condition matches":
      "Wird verwendet, wenn keine andere Bedingung zutrifft",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "Standardsprache",
  "Target Language": "Zielsprache",
  "Search translations...": "Übersetzungen suchen...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": "@{count} Zeichen",
  "Show less": "Weniger anzeigen",
  "Show more": "Mehr anzeigen",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "Geben Sie den Parameternamen ein, der in der Übersetzung verwendet wird:",
  "e.g., count, number, hours": "z. B. Anzahl, Zahl, Stunden",
  "This parameter will be used in conditions":
      "Dieser Parameter wird in Bedingungen verwendet",
  "Current value:": "Aktueller Wert:",
  "This will become the default condition (_)":
      "Dies wird zur Standardbedingung (_)",
  "Converted to Condition successfully": "Erfolgreich in Bedingung umgewandelt",
  "Continue": "Fortfahren",
  "No valid condition value found": "Kein gültiger Bedingungswert gefunden",
  "Select which condition value to use as the string:":
      "Wählen Sie, welcher Bedingungswert als Zeichenkette verwendet werden soll:",
  "Converted to String using condition \"@{key}\"":
      "In Zeichenkette umgewandelt mit Bedingung \"@{key}\"",
  "Convert": "Umwandeln",
  "Condition updated": "Bedingung aktualisiert",
};
