//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

const enLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "No changes to save",
  "@{count} translation@{plural} saved successfully":
      "@{count} translation@{plural} saved successfully",
  "Changes discarded": "Changes discarded",
  "Language Improver": "Language Improver",
  "No languages available": "No languages available",
  "No translations found": "No translations found",
  "Cancel": "Cancel",
  "Save": "Save",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "Key:",
  "Default": "Default",
  "with Condition": "with Condition",
  "Param: @{param}": "Param: @{param}",
  "Target": "Target",
  "Convert to Condition": "Convert to Condition",
  "Convert to String": "Convert to String",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "Add Condition",
  "Enter condition key:": "Enter condition key:",
  "e.g., 0, 1, _ or default": "e.g., 0, 1, _ or default",
  "Common keys: 0, 1, 2, _ (default)": "Common keys: 0, 1, 2, _ (default)",
  "Condition key cannot be empty": "Condition key cannot be empty",
  "Condition key \"@{key}\" already exists":
      "Condition key \"@{key}\" already exists",
  "Add": "Add",
  "Parameter name cannot be empty": "Parameter name cannot be empty",
  "At least one condition is required": "At least one condition is required",
  "Condition \"@{key}\" cannot be empty":
      "Condition \"@{key}\" cannot be empty",
  "Edit Condition": "Edit Condition",
  "Reference (Default Language)": "Reference (Default Language)",
  "Parameter: @{param}": "Parameter: @{param}",
  "Conditions:": "Conditions:",
  "Parameter Name": "Parameter Name",
  "e.g., count, hours, number": "e.g., count, hours, number",
  "The parameter used in the translation text":
      "The parameter used in the translation text",
  "Conditions": "Conditions",
  "No conditions. Add one to get started.":
      "No conditions. Add one to get started.",
  "DEFAULT": "DEFAULT",
  "Remove Condition": "Remove Condition",
  "Translation Value": "Translation Value",
  "Enter translation for this condition":
      "Enter translation for this condition",
  "Used when no other condition matches":
      "Used when no other condition matches",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "Default Language",
  "Target Language": "Target Language",
  "Search translations...": "Search translations...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": "@{count} chars",
  "Show less": "Show less",
  "Show more": "Show more",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "Enter the parameter name that will be used in the translation:",
  "e.g., count, number, hours": "e.g., count, number, hours",
  "This parameter will be used in conditions":
      "This parameter will be used in conditions",
  "Current value:": "Current value:",
  "This will become the default condition (_)":
      "This will become the default condition (_)",
  "Converted to Condition successfully": "Converted to Condition successfully",
  "Continue": "Continue",
  "No valid condition value found": "No valid condition value found",
  "Select which condition value to use as the string:":
      "Select which condition value to use as the string:",
  "Converted to String using condition \"@{key}\"":
      "Converted to String using condition \"@{key}\"",
  "Convert": "Convert",
  "Condition updated": "Condition updated",
};
