//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

import 'package:language_helper/language_helper.dart';

const esLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "No hay cambios para guardar",
  "@{count} translation@{plural} saved successfully": LanguageConditions(
    param: 'count',
    conditions: {
      '0': '0 traducciones guardadas exitosamente',
      '1': '1 traducción guardada exitosamente',
      '_': '@{count} traducciones guardadas exitosamente',
    },
  ),
  "Changes discarded": "Cambios descartados",
  "Language Improver": "Mejorador de Idioma",
  "No languages available": "No hay idiomas disponibles",
  "No translations found": "No se encontraron traducciones",
  "Cancel": "Cancelar",
  "Save": "Guardar",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "Clave:",
  "Default": "Predeterminado",
  "with Condition": "con Condición",
  "Param: @{param}": "Parámetro: @{param}",
  "Target": "Objetivo",
  "Convert to Condition": "Convertir a Condición",
  "Convert to String": "Convertir a Cadena",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "Agregar Condición",
  "Enter condition key:": "Ingresa la clave de condición:",
  "e.g., 0, 1, _ or default": "p. ej., 0, 1, _ o predeterminado",
  "Common keys: 0, 1, 2, _ (default)":
      "Claves comunes: 0, 1, 2, _ (predeterminado)",
  "Condition key cannot be empty": "La clave de condición no puede estar vacía",
  "Condition key \"@{key}\" already exists":
      "La clave de condición \"@{key}\" ya existe",
  "Add": "Agregar",
  "Parameter name cannot be empty":
      "El nombre del parámetro no puede estar vacío",
  "At least one condition is required": "Se requiere al menos una condición",
  "Condition \"@{key}\" cannot be empty":
      "La condición \"@{key}\" no puede estar vacía",
  "Edit Condition": "Editar Condición",
  "Reference (Default Language)": "Referencia (Idioma Predeterminado)",
  "Parameter: @{param}": "Parámetro: @{param}",
  "Conditions:": "Condiciones:",
  "Parameter Name": "Nombre del Parámetro",
  "e.g., count, hours, number": "p. ej., contador, horas, número",
  "The parameter used in the translation text":
      "El parámetro usado en el texto de traducción",
  "Conditions": "Condiciones",
  "No conditions. Add one to get started.":
      "No hay condiciones. Agrega una para comenzar.",
  "DEFAULT": "PREDETERMINADO",
  "Remove Condition": "Eliminar Condición",
  "Translation Value": "Valor de Traducción",
  "Enter translation for this condition":
      "Ingresa la traducción para esta condición",
  "Used when no other condition matches":
      "Se usa cuando ninguna otra condición coincide",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "Idioma Predeterminado",
  "Target Language": "Idioma Objetivo",
  "Search translations...": "Buscar traducciones...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": LanguageConditions(
    param: 'count',
    conditions: {
      '0': '0 caracteres',
      '1': '1 carácter',
      '_': '@{count} caracteres',
    },
  ),
  "Show less": "Mostrar menos",
  "Show more": "Mostrar más",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "Ingresa el nombre del parámetro que se usará en la traducción:",
  "e.g., count, number, hours": "p. ej., contador, número, horas",
  "This parameter will be used in conditions":
      "Este parámetro se usará en las condiciones",
  "Current value:": "Valor actual:",
  "This will become the default condition (_)":
      "Esto se convertirá en la condición predeterminada (_)",
  "Converted to Condition successfully": "Convertido a Condición exitosamente",
  "Continue": "Continuar",
  "No valid condition value found":
      "No se encontró un valor de condición válido",
  "Select which condition value to use as the string:":
      "Selecciona qué valor de condición usar como cadena:",
  "Converted to String using condition \"@{key}\"":
      "Convertido a Cadena usando la condición \"@{key}\"",
  "Convert": "Convertir",
  "Condition updated": "Condición actualizada",
};
