//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

import 'package:language_helper/language_helper.dart';

const frLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "Aucun changement à enregistrer",
  "@{count} translation@{plural} saved successfully": LanguageConditions(
    param: 'count',
    conditions: {
      '0': '0 traduction enregistrée avec succès',
      '1': '1 traduction enregistrée avec succès',
      '_': '@{count} traductions enregistrées avec succès',
    },
  ),
  "Changes discarded": "Modifications annulées",
  "Language Improver": "Améliorateur de langue",
  "No languages available": "Aucune langue disponible",
  "No translations found": "Aucune traduction trouvée",
  "Cancel": "Annuler",
  "Save": "Enregistrer",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "Clé :",
  "Default": "Par défaut",
  "with Condition": "avec condition",
  "Param: @{param}": "Paramètre : @{param}",
  "Target": "Cible",
  "Convert to Condition": "Convertir en condition",
  "Convert to String": "Convertir en chaîne",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "Ajouter une condition",
  "Enter condition key:": "Entrez la clé de condition :",
  "e.g., 0, 1, _ or default": "p. ex., 0, 1, _ ou default",
  "Common keys: 0, 1, 2, _ (default)":
      "Clés communes : 0, 1, 2, _ (par défaut)",
  "Condition key cannot be empty": "La clé de condition ne peut pas être vide",
  "Condition key \"@{key}\" already exists":
      "La clé de condition \"@{key}\" existe déjà",
  "Add": "Ajouter",
  "Parameter name cannot be empty": "Le nom du paramètre ne peut pas être vide",
  "At least one condition is required": "Au moins une condition est requise",
  "Condition \"@{key}\" cannot be empty":
      "La condition \"@{key}\" ne peut pas être vide",
  "Edit Condition": "Modifier la condition",
  "Reference (Default Language)": "Référence (langue par défaut)",
  "Parameter: @{param}": "Paramètre : @{param}",
  "Conditions:": "Conditions :",
  "Parameter Name": "Nom du paramètre",
  "e.g., count, hours, number": "p. ex., count, hours, number",
  "The parameter used in the translation text":
      "Le paramètre utilisé dans le texte de traduction",
  "Conditions": "Conditions",
  "No conditions. Add one to get started.":
      "Aucune condition. Ajoutez-en une pour commencer.",
  "DEFAULT": "PAR DÉFAUT",
  "Remove Condition": "Supprimer la condition",
  "Translation Value": "Valeur de traduction",
  "Enter translation for this condition":
      "Entrez la traduction pour cette condition",
  "Used when no other condition matches":
      "Utilisé lorsqu'aucune autre condition ne correspond",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "Langue par défaut",
  "Target Language": "Langue cible",
  "Search translations...": "Rechercher des traductions...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": "@{count} caractères",
  "Show less": "Afficher moins",
  "Show more": "Afficher plus",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "Entrez le nom du paramètre qui sera utilisé dans la traduction :",
  "e.g., count, number, hours": "p. ex., count, number, hours",
  "This parameter will be used in conditions":
      "Ce paramètre sera utilisé dans les conditions",
  "Current value:": "Valeur actuelle :",
  "This will become the default condition (_)":
      "Cela deviendra la condition par défaut (_)",
  "Converted to Condition successfully": "Converti en condition avec succès",
  "Continue": "Continuer",
  "No valid condition value found": "Aucune valeur de condition valide trouvée",
  "Select which condition value to use as the string:":
      "Sélectionnez la valeur de condition à utiliser comme chaîne :",
  "Converted to String using condition \"@{key}\"":
      "Converti en chaîne en utilisant la condition \"@{key}\"",
  "Convert": "Convertir",
  "Condition updated": "Condition mise à jour",
};
