//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

import 'package:language_helper/language_helper.dart';

const hiLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "सहेजने के लिए कोई परिवर्तन नहीं",
  "@{count} translation@{plural} saved successfully": LanguageConditions(
    param: 'count',
    conditions: {
      '0': '0 अनुवाद सफलतापूर्वक सहेजे गए',
      '1': '1 अनुवाद सफलतापूर्वक सहेजा गया',
      '_': '@{count} अनुवाद सफलतापूर्वक सहेजे गए',
    },
  ),
  "Changes discarded": "परिवर्तन रद्द कर दिए गए",
  "Language Improver": "भाषा सुधारक",
  "No languages available": "कोई भाषा उपलब्ध नहीं",
  "No translations found": "कोई अनुवाद नहीं मिला",
  "Cancel": "रद्द करें",
  "Save": "सहेजें",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "कुंजी:",
  "Default": "डिफ़ॉल्ट",
  "with Condition": "स्थिति के साथ",
  "Param: @{param}": "पैरामीटर: @{param}",
  "Target": "लक्ष्य",
  "Convert to Condition": "स्थिति में बदलें",
  "Convert to String": "स्ट्रिंग में बदलें",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "स्थिति जोड़ें",
  "Enter condition key:": "स्थिति कुंजी दर्ज करें:",
  "e.g., 0, 1, _ or default": "उदाहरण, 0, 1, _ या default",
  "Common keys: 0, 1, 2, _ (default)": "सामान्य कुंजी: 0, 1, 2, _ (डिफ़ॉल्ट)",
  "Condition key cannot be empty": "स्थिति कुंजी खाली नहीं हो सकती",
  "Condition key \"@{key}\" already exists":
      "स्थिति कुंजी \"@{key}\" पहले से मौजूद है",
  "Add": "जोड़ें",
  "Parameter name cannot be empty": "पैरामीटर नाम खाली नहीं हो सकता",
  "At least one condition is required": "कम से कम एक स्थिति आवश्यक है",
  "Condition \"@{key}\" cannot be empty": "स्थिति \"@{key}\" खाली नहीं हो सकती",
  "Edit Condition": "स्थिति संपादित करें",
  "Reference (Default Language)": "संदर्भ (डिफ़ॉल्ट भाषा)",
  "Parameter: @{param}": "पैरामीटर: @{param}",
  "Conditions:": "स्थितियाँ:",
  "Parameter Name": "पैरामीटर नाम",
  "e.g., count, hours, number": "उदाहरण, count, hours, number",
  "The parameter used in the translation text":
      "अनुवाद पाठ में उपयोग किया जाने वाला पैरामीटर",
  "Conditions": "स्थितियाँ",
  "No conditions. Add one to get started.":
      "कोई स्थिति नहीं। शुरू करने के लिए एक जोड़ें।",
  "DEFAULT": "डिफ़ॉल्ट",
  "Remove Condition": "स्थिति हटाएं",
  "Translation Value": "अनुवाद मान",
  "Enter translation for this condition": "इस स्थिति के लिए अनुवाद दर्ज करें",
  "Used when no other condition matches":
      "उपयोग किया जाता है जब कोई अन्य स्थिति मेल नहीं खाती",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "डिफ़ॉल्ट भाषा",
  "Target Language": "लक्ष्य भाषा",
  "Search translations...": "अनुवाद खोजें...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": LanguageConditions(
    param: 'count',
    conditions: {'0': '0 अक्षर', '1': '1 अक्षर', '_': '@{count} अक्षर'},
  ),
  "Show less": "कम दिखाएं",
  "Show more": "अधिक दिखाएं",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "उस पैरामीटर का नाम दर्ज करें जो अनुवाद में उपयोग किया जाएगा:",
  "e.g., count, number, hours": "उदाहरण, count, number, hours",
  "This parameter will be used in conditions":
      "यह पैरामीटर स्थितियों में उपयोग किया जाएगा",
  "Current value:": "वर्तमान मान:",
  "This will become the default condition (_)":
      "यह डिफ़ॉल्ट स्थिति (_) बन जाएगी",
  "Converted to Condition successfully": "स्थिति में सफलतापूर्वक बदल दिया गया",
  "Continue": "जारी रखें",
  "No valid condition value found": "कोई वैध स्थिति मान नहीं मिला",
  "Select which condition value to use as the string:":
      "चुनें कि स्ट्रिंग के रूप में किस स्थिति मान का उपयोग करना है:",
  "Converted to String using condition \"@{key}\"":
      "स्थिति \"@{key}\" का उपयोग करके स्ट्रिंग में बदल दिया गया",
  "Convert": "बदलें",
  "Condition updated": "स्थिति अपडेट की गई",
};
