//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

const idLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "Tidak ada perubahan untuk disimpan",
  "@{count} translation@{plural} saved successfully":
      "@{count} terjemahan berhasil disimpan",
  "Changes discarded": "Perubahan dibatalkan",
  "Language Improver": "Peningkat Bahasa",
  "No languages available": "Tidak ada bahasa tersedia",
  "No translations found": "Tidak ada terjemahan ditemukan",
  "Cancel": "Batal",
  "Save": "Simpan",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "Kunci:",
  "Default": "Default",
  "with Condition": "dengan Condition",
  "Param: @{param}": "Param: @{param}",
  "Target": "Target",
  "Convert to Condition": "Ubah ke Condition",
  "Convert to String": "Ubah ke String",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "Tambah Condition",
  "Enter condition key:": "Masukkan kunci kondisi:",
  "e.g., 0, 1, _ or default": "mis., 0, 1, _ atau default",
  "Common keys: 0, 1, 2, _ (default)": "Kunci umum: 0, 1, 2, _ (default)",
  "Condition key cannot be empty": "Kunci kondisi tidak boleh kosong",
  "Condition key \"@{key}\" already exists":
      "Kunci kondisi \"@{key}\" sudah ada",
  "Add": "Tambah",
  "Parameter name cannot be empty": "Nama parameter tidak boleh kosong",
  "At least one condition is required": "Setidaknya satu kondisi diperlukan",
  "Condition \"@{key}\" cannot be empty":
      "Kondisi \"@{key}\" tidak boleh kosong",
  "Edit Condition": "Edit Condition",
  "Reference (Default Language)": "Referensi (Bahasa Default)",
  "Parameter: @{param}": "Parameter: @{param}",
  "Conditions:": "Kondisi:",
  "Parameter Name": "Nama Parameter",
  "e.g., count, hours, number": "mis., count, hours, number",
  "The parameter used in the translation text":
      "Parameter yang digunakan dalam teks terjemahan",
  "Conditions": "Kondisi",
  "No conditions. Add one to get started.":
      "Tidak ada kondisi. Tambahkan satu untuk memulai.",
  "DEFAULT": "DEFAULT",
  "Remove Condition": "Hapus Condition",
  "Translation Value": "Nilai Terjemahan",
  "Enter translation for this condition":
      "Masukkan terjemahan untuk kondisi ini",
  "Used when no other condition matches":
      "Digunakan ketika tidak ada kondisi lain yang cocok",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "Bahasa Default",
  "Target Language": "Bahasa Target",
  "Search translations...": "Cari terjemahan...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": "@{count} karakter",
  "Show less": "Tampilkan lebih sedikit",
  "Show more": "Tampilkan lebih banyak",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "Masukkan nama parameter yang akan digunakan dalam terjemahan:",
  "e.g., count, number, hours": "mis., count, number, hours",
  "This parameter will be used in conditions":
      "Parameter ini akan digunakan dalam kondisi",
  "Current value:": "Nilai saat ini:",
  "This will become the default condition (_)":
      "Ini akan menjadi kondisi default (_)",
  "Converted to Condition successfully": "Berhasil diubah ke Condition",
  "Continue": "Lanjutkan",
  "No valid condition value found":
      "Tidak ada nilai kondisi yang valid ditemukan",
  "Select which condition value to use as the string:":
      "Pilih nilai kondisi mana yang akan digunakan sebagai string:",
  "Converted to String using condition \"@{key}\"":
      "Diubah ke String menggunakan kondisi \"@{key}\"",
  "Convert": "Ubah",
  "Condition updated": "Kondisi diperbarui",
};
