//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

import 'package:language_helper/language_helper.dart';

const itLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "Nessuna modifica da salvare",
  "@{count} translation@{plural} saved successfully": LanguageConditions(
    param: 'count',
    conditions: {
      '0': '0 traduzioni salvate con successo',
      '1': '1 traduzione salvata con successo',
      '_': '@{count} traduzioni salvate con successo',
    },
  ),
  "Changes discarded": "Modifiche scartate",
  "Language Improver": "Miglioratore di Lingua",
  "No languages available": "Nessuna lingua disponibile",
  "No translations found": "Nessuna traduzione trovata",
  "Cancel": "Annulla",
  "Save": "Salva",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "Chiave:",
  "Default": "Predefinito",
  "with Condition": "con Condizione",
  "Param: @{param}": "Param: @{param}",
  "Target": "Destinazione",
  "Convert to Condition": "Converti in Condizione",
  "Convert to String": "Converti in Stringa",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "Aggiungi Condizione",
  "Enter condition key:": "Inserisci chiave di condizione:",
  "e.g., 0, 1, _ or default": "es. 0, 1, _ o predefinito",
  "Common keys: 0, 1, 2, _ (default)":
      "Chiavi comuni: 0, 1, 2, _ (predefinito)",
  "Condition key cannot be empty":
      "La chiave di condizione non può essere vuota",
  "Condition key \"@{key}\" already exists":
      "La chiave di condizione \"@{key}\" esiste già",
  "Add": "Aggiungi",
  "Parameter name cannot be empty":
      "Il nome del parametro non può essere vuoto",
  "At least one condition is required": "È richiesta almeno una condizione",
  "Condition \"@{key}\" cannot be empty":
      "La condizione \"@{key}\" non può essere vuota",
  "Edit Condition": "Modifica Condizione",
  "Reference (Default Language)": "Riferimento (Lingua Predefinita)",
  "Parameter: @{param}": "Parametro: @{param}",
  "Conditions:": "Condizioni:",
  "Parameter Name": "Nome Parametro",
  "e.g., count, hours, number": "es. conteggio, ore, numero",
  "The parameter used in the translation text":
      "Il parametro utilizzato nel testo della traduzione",
  "Conditions": "Condizioni",
  "No conditions. Add one to get started.":
      "Nessuna condizione. Aggiungine una per iniziare.",
  "DEFAULT": "PREDEFINITO",
  "Remove Condition": "Rimuovi Condizione",
  "Translation Value": "Valore Traduzione",
  "Enter translation for this condition":
      "Inserisci la traduzione per questa condizione",
  "Used when no other condition matches":
      "Utilizzato quando nessun'altra condizione corrisponde",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "Lingua Predefinita",
  "Target Language": "Lingua di Destinazione",
  "Search translations...": "Cerca traduzioni...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": "@{count} caratteri",
  "Show less": "Mostra meno",
  "Show more": "Mostra di più",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "Inserisci il nome del parametro che verrà utilizzato nella traduzione:",
  "e.g., count, number, hours": "es. conteggio, numero, ore",
  "This parameter will be used in conditions":
      "Questo parametro verrà utilizzato nelle condizioni",
  "Current value:": "Valore attuale:",
  "This will become the default condition (_)":
      "Questo diventerà la condizione predefinita (_)",
  "Converted to Condition successfully":
      "Convertito in Condizione con successo",
  "Continue": "Continua",
  "No valid condition value found":
      "Nessun valore di condizione valido trovato",
  "Select which condition value to use as the string:":
      "Seleziona quale valore di condizione utilizzare come stringa:",
  "Converted to String using condition \"@{key}\"":
      "Convertito in Stringa utilizzando la condizione \"@{key}\"",
  "Convert": "Converti",
  "Condition updated": "Condizione aggiornata",
};
