//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

const jaLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "保存する変更がありません",
  "@{count} translation@{plural} saved successfully": "@{count}件の翻訳が正常に保存されました",
  "Changes discarded": "変更が破棄されました",
  "Language Improver": "言語改善ツール",
  "No languages available": "利用可能な言語がありません",
  "No translations found": "翻訳が見つかりませんでした",
  "Cancel": "キャンセル",
  "Save": "保存",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "キー:",
  "Default": "デフォルト",
  "with Condition": "条件付き",
  "Param: @{param}": "パラメータ: @{param}",
  "Target": "対象",
  "Convert to Condition": "条件に変換",
  "Convert to String": "文字列に変換",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "条件を追加",
  "Enter condition key:": "条件キーを入力してください:",
  "e.g., 0, 1, _ or default": "例: 0, 1, _ または default",
  "Common keys: 0, 1, 2, _ (default)": "一般的なキー: 0, 1, 2, _ (デフォルト)",
  "Condition key cannot be empty": "条件キーは空にできません",
  "Condition key \"@{key}\" already exists": "条件キー \"@{key}\" は既に存在します",
  "Add": "追加",
  "Parameter name cannot be empty": "パラメータ名は空にできません",
  "At least one condition is required": "少なくとも1つの条件が必要です",
  "Condition \"@{key}\" cannot be empty": "条件 \"@{key}\" は空にできません",
  "Edit Condition": "条件を編集",
  "Reference (Default Language)": "参照 (デフォルト言語)",
  "Parameter: @{param}": "パラメータ: @{param}",
  "Conditions:": "条件:",
  "Parameter Name": "パラメータ名",
  "e.g., count, hours, number": "例: count, hours, number",
  "The parameter used in the translation text": "翻訳テキストで使用されるパラメータ",
  "Conditions": "条件",
  "No conditions. Add one to get started.": "条件がありません。開始するには追加してください。",
  "DEFAULT": "デフォルト",
  "Remove Condition": "条件を削除",
  "Translation Value": "翻訳値",
  "Enter translation for this condition": "この条件の翻訳を入力してください",
  "Used when no other condition matches": "他の条件が一致しない場合に使用されます",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "デフォルト言語",
  "Target Language": "対象言語",
  "Search translations...": "翻訳を検索...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": "@{count}文字",
  "Show less": "少なく表示",
  "Show more": "もっと表示",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "翻訳で使用するパラメータ名を入力してください:",
  "e.g., count, number, hours": "例: count, number, hours",
  "This parameter will be used in conditions": "このパラメータは条件で使用されます",
  "Current value:": "現在の値:",
  "This will become the default condition (_)": "これはデフォルト条件 (_) になります",
  "Converted to Condition successfully": "条件への変換が完了しました",
  "Continue": "続ける",
  "No valid condition value found": "有効な条件値が見つかりませんでした",
  "Select which condition value to use as the string:":
      "文字列として使用する条件値を選択してください:",
  "Converted to String using condition \"@{key}\"":
      "条件 \"@{key}\" を使用して文字列に変換しました",
  "Convert": "変換",
  "Condition updated": "条件が更新されました",
};
