//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

const koLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "저장할 변경 사항 없음",
  "@{count} translation@{plural} saved successfully":
      "@{count}개의 번역이 성공적으로 저장되었습니다",
  "Changes discarded": "변경 사항 취소됨",
  "Language Improver": "언어 개선 도구",
  "No languages available": "사용 가능한 언어가 없습니다",
  "No translations found": "번역을 찾을 수 없습니다",
  "Cancel": "취소",
  "Save": "저장",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "키:",
  "Default": "기본값",
  "with Condition": "조건 포함",
  "Param: @{param}": "매개변수: @{param}",
  "Target": "대상",
  "Convert to Condition": "조건으로 변환",
  "Convert to String": "문자열로 변환",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "조건 추가",
  "Enter condition key:": "조건 키를 입력하세요:",
  "e.g., 0, 1, _ or default": "예: 0, 1, _ 또는 default",
  "Common keys: 0, 1, 2, _ (default)": "일반 키: 0, 1, 2, _ (기본값)",
  "Condition key cannot be empty": "조건 키는 비어 있을 수 없습니다",
  "Condition key \"@{key}\" already exists": "조건 키 \"@{key}\"이(가) 이미 존재합니다",
  "Add": "추가",
  "Parameter name cannot be empty": "매개변수 이름은 비어 있을 수 없습니다",
  "At least one condition is required": "최소 하나의 조건이 필요합니다",
  "Condition \"@{key}\" cannot be empty": "조건 \"@{key}\"은(는) 비어 있을 수 없습니다",
  "Edit Condition": "조건 편집",
  "Reference (Default Language)": "참조 (기본 언어)",
  "Parameter: @{param}": "매개변수: @{param}",
  "Conditions:": "조건:",
  "Parameter Name": "매개변수 이름",
  "e.g., count, hours, number": "예: count, hours, number",
  "The parameter used in the translation text": "번역 텍스트에서 사용되는 매개변수",
  "Conditions": "조건",
  "No conditions. Add one to get started.": "조건이 없습니다. 시작하려면 하나를 추가하세요.",
  "DEFAULT": "기본값",
  "Remove Condition": "조건 제거",
  "Translation Value": "번역 값",
  "Enter translation for this condition": "이 조건에 대한 번역을 입력하세요",
  "Used when no other condition matches": "다른 조건이 일치하지 않을 때 사용됨",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "기본 언어",
  "Target Language": "대상 언어",
  "Search translations...": "번역 검색...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": "@{count}자",
  "Show less": "간략히 보기",
  "Show more": "자세히 보기",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "번역에 사용할 매개변수 이름을 입력하세요:",
  "e.g., count, number, hours": "예: count, number, hours",
  "This parameter will be used in conditions": "이 매개변수는 조건에서 사용됩니다",
  "Current value:": "현재 값:",
  "This will become the default condition (_)": "이것은 기본 조건(_)이 됩니다",
  "Converted to Condition successfully": "조건으로 성공적으로 변환되었습니다",
  "Continue": "계속",
  "No valid condition value found": "유효한 조건 값이 없습니다",
  "Select which condition value to use as the string:": "문자열로 사용할 조건 값을 선택하세요:",
  "Converted to String using condition \"@{key}\"":
      "조건 \"@{key}\"을 사용하여 문자열로 변환되었습니다",
  "Convert": "변환",
  "Condition updated": "조건이 업데이트되었습니다",
};
