//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

import 'package:language_helper/language_helper.dart';

const ptLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "Nenhuma alteração para salvar",
  "@{count} translation@{plural} saved successfully": LanguageConditions(
    param: 'count',
    conditions: {
      '0': '0 traduções salvas com sucesso',
      '1': '1 tradução salva com sucesso',
      '_': '@{count} traduções salvas com sucesso',
    },
  ),
  "Changes discarded": "Alterações descartadas",
  "Language Improver": "Language Improver",
  "No languages available": "Nenhum idioma disponível",
  "No translations found": "Nenhuma tradução encontrada",
  "Cancel": "Cancelar",
  "Save": "Salvar",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "Chave:",
  "Default": "Padrão",
  "with Condition": "com Condição",
  "Param: @{param}": "Parâmetro: @{param}",
  "Target": "Destino",
  "Convert to Condition": "Converter para Condition",
  "Convert to String": "Converter para String",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "Adicionar Condition",
  "Enter condition key:": "Digite a chave da condição:",
  "e.g., 0, 1, _ or default": "ex.: 0, 1, _ ou default",
  "Common keys: 0, 1, 2, _ (default)": "Chaves comuns: 0, 1, 2, _ (padrão)",
  "Condition key cannot be empty": "A chave da condição não pode estar vazia",
  "Condition key \"@{key}\" already exists":
      "A chave de condição \"@{key}\" já existe",
  "Add": "Adicionar",
  "Parameter name cannot be empty": "O nome do parâmetro não pode estar vazio",
  "At least one condition is required": "Pelo menos uma condição é necessária",
  "Condition \"@{key}\" cannot be empty":
      "A condição \"@{key}\" não pode estar vazia",
  "Edit Condition": "Editar Condition",
  "Reference (Default Language)": "Referência (Idioma Padrão)",
  "Parameter: @{param}": "Parâmetro: @{param}",
  "Conditions:": "Condições:",
  "Parameter Name": "Nome do Parâmetro",
  "e.g., count, hours, number": "ex.: count, hours, number",
  "The parameter used in the translation text":
      "O parâmetro usado no texto da tradução",
  "Conditions": "Condições",
  "No conditions. Add one to get started.":
      "Nenhuma condição. Adicione uma para começar.",
  "DEFAULT": "PADRÃO",
  "Remove Condition": "Remover Condition",
  "Translation Value": "Valor da Tradução",
  "Enter translation for this condition":
      "Digite a tradução para esta condição",
  "Used when no other condition matches":
      "Usado quando nenhuma outra condição corresponde",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "Idioma Padrão",
  "Target Language": "Idioma de Destino",
  "Search translations...": "Buscar traduções...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": "@{count} caracteres",
  "Show less": "Mostrar menos",
  "Show more": "Mostrar mais",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "Digite o nome do parâmetro que será usado na tradução:",
  "e.g., count, number, hours": "ex.: count, number, hours",
  "This parameter will be used in conditions":
      "Este parâmetro será usado nas condições",
  "Current value:": "Valor atual:",
  "This will become the default condition (_)":
      "Isso se tornará a condição padrão (_)",
  "Converted to Condition successfully":
      "Convertido para Condition com sucesso",
  "Continue": "Continuar",
  "No valid condition value found":
      "Nenhum valor de condição válido encontrado",
  "Select which condition value to use as the string:":
      "Selecione qual valor de condição usar como string:",
  "Converted to String using condition \"@{key}\"":
      "Convertido para String usando a condição \"@{key}\"",
  "Convert": "Converter",
  "Condition updated": "Condição atualizada",
};
