//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

import 'package:language_helper/language_helper.dart';

const ruLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "Нет изменений для сохранения",
  "@{count} translation@{plural} saved successfully": LanguageConditions(
    param: 'count',
    conditions: {
      '0': '0 переводов успешно сохранено',
      '1': '1 перевод успешно сохранён',
      '2': '2 перевода успешно сохранены',
      '3': '3 перевода успешно сохранены',
      '4': '4 перевода успешно сохранены',
      '_': '@{count} переводов успешно сохранено',
    },
  ),
  "Changes discarded": "Изменения отменены",
  "Language Improver": "Улучшитель языков",
  "No languages available": "Нет доступных языков",
  "No translations found": "Переводы не найдены",
  "Cancel": "Отмена",
  "Save": "Сохранить",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "Ключ:",
  "Default": "По умолчанию",
  "with Condition": "с условием",
  "Param: @{param}": "Параметр: @{param}",
  "Target": "Целевой",
  "Convert to Condition": "Преобразовать в условие",
  "Convert to String": "Преобразовать в строку",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "Добавить условие",
  "Enter condition key:": "Введите ключ условия:",
  "e.g., 0, 1, _ or default": "например, 0, 1, _ или по умолчанию",
  "Common keys: 0, 1, 2, _ (default)": "Общие ключи: 0, 1, 2, _ (по умолчанию)",
  "Condition key cannot be empty": "Ключ условия не может быть пустым",
  "Condition key \"@{key}\" already exists":
      "Ключ условия \"@{key}\" уже существует",
  "Add": "Добавить",
  "Parameter name cannot be empty": "Имя параметра не может быть пустым",
  "At least one condition is required": "Требуется хотя бы одно условие",
  "Condition \"@{key}\" cannot be empty":
      "Условие \"@{key}\" не может быть пустым",
  "Edit Condition": "Редактировать условие",
  "Reference (Default Language)": "Справочник (Язык по умолчанию)",
  "Parameter: @{param}": "Параметр: @{param}",
  "Conditions:": "Условия:",
  "Parameter Name": "Имя параметра",
  "e.g., count, hours, number": "например, количество, часы, число",
  "The parameter used in the translation text":
      "Параметр, используемый в тексте перевода",
  "Conditions": "Условия",
  "No conditions. Add one to get started.":
      "Нет условий. Добавьте одно для начала.",
  "DEFAULT": "ПО УМОЛЧАНИЮ",
  "Remove Condition": "Удалить условие",
  "Translation Value": "Значение перевода",
  "Enter translation for this condition": "Введите перевод для этого условия",
  "Used when no other condition matches":
      "Используется, когда никакое другое условие не совпадает",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "Язык по умолчанию",
  "Target Language": "Целевой язык",
  "Search translations...": "Поиск переводов...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": LanguageConditions(
    param: 'count',
    conditions: {
      '0': '0 символов',
      '1': '1 символ',
      '2': '2 символа',
      '3': '3 символа',
      '4': '4 символа',
      '_': '@{count} символов',
    },
  ),
  "Show less": "Показать меньше",
  "Show more": "Показать больше",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "Введите имя параметра, который будет использоваться в переводе:",
  "e.g., count, number, hours": "например, количество, число, часы",
  "This parameter will be used in conditions":
      "Этот параметр будет использоваться в условиях",
  "Current value:": "Текущее значение:",
  "This will become the default condition (_)":
      "Это станет условием по умолчанию (_)",
  "Converted to Condition successfully": "Успешно преобразовано в условие",
  "Continue": "Продолжить",
  "No valid condition value found": "Не найдено допустимое значение условия",
  "Select which condition value to use as the string:":
      "Выберите значение условия для использования в качестве строки:",
  "Converted to String using condition \"@{key}\"":
      "Преобразовано в строку с использованием условия \"@{key}\"",
  "Convert": "Преобразовать",
  "Condition updated": "Условие обновлено",
};
