//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

const trLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "Kaydedilecek değişiklik yok",
  "@{count} translation@{plural} saved successfully":
      "@{count} çeviri başarıyla kaydedildi",
  "Changes discarded": "Değişiklikler iptal edildi",
  "Language Improver": "Dil İyileştirici",
  "No languages available": "Kullanılabilir dil yok",
  "No translations found": "Çeviri bulunamadı",
  "Cancel": "İptal",
  "Save": "Kaydet",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "Anahtar:",
  "Default": "Varsayılan",
  "with Condition": "Koşullu",
  "Param: @{param}": "Parametre: @{param}",
  "Target": "Hedef",
  "Convert to Condition": "Koşula Dönüştür",
  "Convert to String": "Metne Dönüştür",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "Koşul Ekle",
  "Enter condition key:": "Koşul anahtarı girin:",
  "e.g., 0, 1, _ or default": "örn. 0, 1, _ veya default",
  "Common keys: 0, 1, 2, _ (default)":
      "Yaygın anahtarlar: 0, 1, 2, _ (varsayılan)",
  "Condition key cannot be empty": "Koşul anahtarı boş olamaz",
  "Condition key \"@{key}\" already exists":
      "Koşul anahtarı \"@{key}\" zaten mevcut",
  "Add": "Ekle",
  "Parameter name cannot be empty": "Parametre adı boş olamaz",
  "At least one condition is required": "En az bir koşul gerekli",
  "Condition \"@{key}\" cannot be empty": "Koşul \"@{key}\" boş olamaz",
  "Edit Condition": "Koşulu Düzenle",
  "Reference (Default Language)": "Referans (Varsayılan Dil)",
  "Parameter: @{param}": "Parametre: @{param}",
  "Conditions:": "Koşullar:",
  "Parameter Name": "Parametre Adı",
  "e.g., count, hours, number": "örn. count, hours, number",
  "The parameter used in the translation text":
      "Çeviri metninde kullanılan parametre",
  "Conditions": "Koşullar",
  "No conditions. Add one to get started.":
      "Koşul yok. Başlamak için bir tane ekleyin.",
  "DEFAULT": "VARSAYILAN",
  "Remove Condition": "Koşulu Kaldır",
  "Translation Value": "Çeviri Değeri",
  "Enter translation for this condition": "Bu koşul için çeviri girin",
  "Used when no other condition matches":
      "Başka koşul eşleşmediğinde kullanılır",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "Varsayılan Dil",
  "Target Language": "Hedef Dil",
  "Search translations...": "Çevirileri ara...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": "@{count} karakter",
  "Show less": "Daha az göster",
  "Show more": "Daha fazla göster",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "Çeviride kullanılacak parametre adını girin:",
  "e.g., count, number, hours": "örn. count, number, hours",
  "This parameter will be used in conditions":
      "Bu parametre koşullarda kullanılacak",
  "Current value:": "Mevcut değer:",
  "This will become the default condition (_)":
      "Bu varsayılan koşul (_) olacak",
  "Converted to Condition successfully": "Koşula başarıyla dönüştürüldü",
  "Continue": "Devam Et",
  "No valid condition value found": "Geçerli koşul değeri bulunamadı",
  "Select which condition value to use as the string:":
      "Metin olarak kullanılacak koşul değerini seçin:",
  "Converted to String using condition \"@{key}\"":
      "Koşul \"@{key}\" kullanılarak metne dönüştürüldü",
  "Convert": "Dönüştür",
  "Condition updated": "Koşul güncellendi",
};
