//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

import 'package:language_helper/language_helper.dart';

const viLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "Không có thay đổi để lưu",
  "@{count} translation@{plural} saved successfully": LanguageConditions(
    param: 'count',
    conditions: {
      '0': '0 bản dịch đã được lưu thành công',
      '1': '1 bản dịch đã được lưu thành công',
      '_': '@{count} bản dịch đã được lưu thành công',
    },
  ),
  "Changes discarded": "Thay đổi đã bị hủy",
  "Language Improver": "Cải thiện Ngôn ngữ",
  "No languages available": "Không có ngôn ngữ nào khả dụng",
  "No translations found": "Không tìm thấy bản dịch",
  "Cancel": "Hủy",
  "Save": "Lưu",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "Khóa:",
  "Default": "Mặc định",
  "with Condition": "có Điều kiện",
  "Param: @{param}": "Tham số: @{param}",
  "Target": "Đích",
  "Convert to Condition": "Chuyển đổi thành Điều kiện",
  "Convert to String": "Chuyển đổi thành Chuỗi",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "Thêm Điều kiện",
  "Enter condition key:": "Nhập khóa điều kiện:",
  "e.g., 0, 1, _ or default": "ví dụ: 0, 1, _ hoặc default",
  "Common keys: 0, 1, 2, _ (default)":
      "Khóa thường dùng: 0, 1, 2, _ (mặc định)",
  "Condition key cannot be empty": "Khóa điều kiện không thể để trống",
  "Condition key \"@{key}\" already exists":
      "Khóa điều kiện \"@{key}\" đã tồn tại",
  "Add": "Thêm",
  "Parameter name cannot be empty": "Tên tham số không thể để trống",
  "At least one condition is required": "Cần ít nhất một điều kiện",
  "Condition \"@{key}\" cannot be empty":
      "Điều kiện \"@{key}\" không thể để trống",
  "Edit Condition": "Chỉnh sửa Điều kiện",
  "Reference (Default Language)": "Tham chiếu (Ngôn ngữ Mặc định)",
  "Parameter: @{param}": "Tham số: @{param}",
  "Conditions:": "Điều kiện:",
  "Parameter Name": "Tên Tham số",
  "e.g., count, hours, number": "ví dụ: count, hours, number",
  "The parameter used in the translation text":
      "Tham số được sử dụng trong văn bản dịch",
  "Conditions": "Điều kiện",
  "No conditions. Add one to get started.":
      "Không có điều kiện. Thêm một điều kiện để bắt đầu.",
  "DEFAULT": "MẶC ĐỊNH",
  "Remove Condition": "Xóa Điều kiện",
  "Translation Value": "Giá trị Bản dịch",
  "Enter translation for this condition": "Nhập bản dịch cho điều kiện này",
  "Used when no other condition matches":
      "Được sử dụng khi không có điều kiện nào khác khớp",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "Ngôn ngữ Mặc định",
  "Target Language": "Ngôn ngữ Đích",
  "Search translations...": "Tìm kiếm bản dịch...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": LanguageConditions(
    param: 'count',
    conditions: {'0': '0 ký tự', '1': '1 ký tự', '_': '@{count} ký tự'},
  ),
  "Show less": "Hiển thị ít hơn",
  "Show more": "Hiển thị thêm",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "Nhập tên tham số sẽ được sử dụng trong bản dịch:",
  "e.g., count, number, hours": "ví dụ: count, number, hours",
  "This parameter will be used in conditions":
      "Tham số này sẽ được sử dụng trong các điều kiện",
  "Current value:": "Giá trị hiện tại:",
  "This will become the default condition (_)":
      "Điều này sẽ trở thành điều kiện mặc định (_)",
  "Converted to Condition successfully":
      "Đã chuyển đổi thành Điều kiện thành công",
  "Continue": "Tiếp tục",
  "No valid condition value found": "Không tìm thấy giá trị điều kiện hợp lệ",
  "Select which condition value to use as the string:":
      "Chọn giá trị điều kiện nào sẽ được sử dụng làm chuỗi:",
  "Converted to String using condition \"@{key}\"":
      "Đã chuyển đổi thành Chuỗi bằng điều kiện \"@{key}\"",
  "Convert": "Chuyển đổi",
  "Condition updated": "Điều kiện đã được cập nhật",
};
