//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

const zhLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "没有需要保存的更改",
  "@{count} translation@{plural} saved successfully": "@{count} 条翻译保存成功",
  "Changes discarded": "更改已丢弃",
  "Language Improver": "语言改进器",
  "No languages available": "没有可用的语言",
  "No translations found": "未找到翻译",
  "Cancel": "取消",
  "Save": "保存",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "键：",
  "Default": "默认",
  "with Condition": "有条件",
  "Param: @{param}": "参数：@{param}",
  "Target": "目标",
  "Convert to Condition": "转换为条件",
  "Convert to String": "转换为字符串",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "添加条件",
  "Enter condition key:": "输入条件键：",
  "e.g., 0, 1, _ or default": "例如：0、1、_ 或 default",
  "Common keys: 0, 1, 2, _ (default)": "常用键：0、1、2、_（默认）",
  "Condition key cannot be empty": "条件键不能为空",
  "Condition key \"@{key}\" already exists": "条件键 \"@{key}\" 已存在",
  "Add": "添加",
  "Parameter name cannot be empty": "参数名称不能为空",
  "At least one condition is required": "至少需要一个条件",
  "Condition \"@{key}\" cannot be empty": "条件 \"@{key}\" 不能为空",
  "Edit Condition": "编辑条件",
  "Reference (Default Language)": "参考（默认语言）",
  "Parameter: @{param}": "参数：@{param}",
  "Conditions:": "条件：",
  "Parameter Name": "参数名称",
  "e.g., count, hours, number": "例如：count、hours、number",
  "The parameter used in the translation text": "翻译文本中使用的参数",
  "Conditions": "条件",
  "No conditions. Add one to get started.": "没有条件。请添加一个以开始。",
  "DEFAULT": "默认",
  "Remove Condition": "删除条件",
  "Translation Value": "翻译值",
  "Enter translation for this condition": "输入此条件的翻译",
  "Used when no other condition matches": "当没有其他条件匹配时使用",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "默认语言",
  "Target Language": "目标语言",
  "Search translations...": "搜索翻译...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": "@{count} 个字符",
  "Show less": "显示更少",
  "Show more": "显示更多",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "输入将在翻译中使用的参数名称：",
  "e.g., count, number, hours": "例如：count、number、hours",
  "This parameter will be used in conditions": "此参数将在条件中使用",
  "Current value:": "当前值：",
  "This will become the default condition (_)": "这将成为默认条件 (_)",
  "Converted to Condition successfully": "成功转换为条件",
  "Continue": "继续",
  "No valid condition value found": "未找到有效的条件值",
  "Select which condition value to use as the string:": "选择要用作字符串的条件值：",
  "Converted to String using condition \"@{key}\"": "使用条件 \"@{key}\" 转换为字符串",
  "Convert": "转换",
  "Condition updated": "条件已更新",
};
