//==============================================================================
// Generated Date: 2025-11-03T18:51:50.514967
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

const zhTWLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: src/language_improver.dart
  ///===========================================================================
  "@path_src/language_improver.dart": "",
  "No changes to save": "無需儲存的變更",
  "@{count} translation@{plural} saved successfully": "已成功儲存 @{count} 個翻譯",
  "Changes discarded": "變更已放棄",
  "Language Improver": "語言改進工具",
  "No languages available": "無可用語言",
  "No translations found": "找不到翻譯",
  "Cancel": "取消",
  "Save": "儲存",

  ///===========================================================================
  /// Path: src/translation_card.dart
  ///===========================================================================
  "@path_src/translation_card.dart": "",
  "Key:": "鍵：",
  "Default": "預設",
  "with Condition": "有條件",
  "Param: @{param}": "參數：@{param}",
  "Target": "目標",
  "Convert to Condition": "轉換為條件",
  "Convert to String": "轉換為字串",
  "null": "null",

  ///===========================================================================
  /// Path: src/language_condition_editor_dialog.dart
  ///===========================================================================
  "@path_src/language_condition_editor_dialog.dart": "",
  "Add Condition": "新增條件",
  "Enter condition key:": "輸入條件鍵：",
  "e.g., 0, 1, _ or default": "例如：0、1、_ 或 default",
  "Common keys: 0, 1, 2, _ (default)": "常用鍵：0、1、2、_（預設）",
  "Condition key cannot be empty": "條件鍵不能為空",
  "Condition key \"@{key}\" already exists": "條件鍵 \"@{key}\" 已存在",
  "Add": "新增",
  "Parameter name cannot be empty": "參數名稱不能為空",
  "At least one condition is required": "至少需要一個條件",
  "Condition \"@{key}\" cannot be empty": "條件 \"@{key}\" 不能為空",
  "Edit Condition": "編輯條件",
  "Reference (Default Language)": "參考（預設語言）",
  "Parameter: @{param}": "參數：@{param}",
  "Conditions:": "條件：",
  "Parameter Name": "參數名稱",
  "e.g., count, hours, number": "例如：count、hours、number",
  "The parameter used in the translation text": "翻譯文字中使用的參數",
  "Conditions": "條件",
  "No conditions. Add one to get started.": "尚無條件。新增一個以開始。",
  "DEFAULT": "預設",
  "Remove Condition": "移除條件",
  "Translation Value": "翻譯值",
  "Enter translation for this condition": "輸入此條件的翻譯",
  "Used when no other condition matches": "當沒有其他條件符合時使用",

  ///===========================================================================
  /// Path: src/language_improver_app_bar.dart
  ///===========================================================================
  "@path_src/language_improver_app_bar.dart": "",
  "Default Language": "預設語言",
  "Target Language": "目標語言",
  "Search translations...": "搜尋翻譯...",

  ///===========================================================================
  /// Path: src/expandable_text.dart
  ///===========================================================================
  "@path_src/expandable_text.dart": "",
  "@{count} chars": "@{count} 個字元",
  "Show less": "顯示較少",
  "Show more": "顯示更多",

  ///===========================================================================
  /// Path: src/translation_conversion.dart
  ///===========================================================================
  "@path_src/translation_conversion.dart": "",
  "Enter the parameter name that will be used in the translation:":
      "輸入將在翻譯中使用的參數名稱：",
  "e.g., count, number, hours": "例如：count、number、hours",
  "This parameter will be used in conditions": "此參數將用於條件中",
  "Current value:": "目前值：",
  "This will become the default condition (_)": "這將成為預設條件 (_)",
  "Converted to Condition successfully": "已成功轉換為條件",
  "Continue": "繼續",
  "No valid condition value found": "找不到有效的條件值",
  "Select which condition value to use as the string:": "選擇要作為字串使用的條件值：",
  "Converted to String using condition \"@{key}\"": "已使用條件 \"@{key}\" 轉換為字串",
  "Convert": "轉換",
  "Condition updated": "條件已更新",
};
