//==============================================================================
// Generated Date: 2025-11-27T10:46:02.214025
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

import 'package:language_helper/language_helper.dart';

const enLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: main.dart
  ///===========================================================================
  "@path_main.dart": "",
  "Welcome": 'Welcome',
  "Hello": 'Hello',
  "Goodbye": 'Goodbye',
  "Thank you": 'Thank you',
  "Please": 'Please',
  "@{count} items": LanguageConditions(
    param: 'count',
    conditions: {'0': 'No items', '1': '1 item', '_': '@{count} items'},
  ),
  "Hello, @{name}!": 'Hello, @{name}!',
  "Settings": 'Settings',
  "Language": 'Language',
  "Theme": 'Theme',
  "About": 'About',
  "Profile": 'Profile',
  "Logout": 'Logout',
};
