//==============================================================================
// Generated Date: 2025-11-27T10:46:02.214025
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

import 'package:language_helper/language_helper.dart';

const viLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: main.dart
  ///===========================================================================
  "@path_main.dart": "",
  "Welcome": 'Chào mừng',
  "Hello": 'Xin chào',
  "Goodbye": 'Tạm biệt',
  "Thank you": 'Cảm ơn',
  "Please": 'Xin lỗi',
  "@{count} items": LanguageConditions(
    param: 'count',
    conditions: {'0': 'Không có mục', '1': '1 mục', '_': '@{count} mục'},
  ),
  "Hello, @{name}!": 'Xin chào, @{name}!',
  "Settings": 'Cài đặt',
  "Language": 'Ngôn ngữ',
  "Theme": 'Giao diện',
  "About": 'Giới thiệu',
  "Profile": 'Hồ sơ',
  "Logout": 'Đăng xuất',
};
