//==============================================================================
// Generated Date: 2025-11-27T10:46:02.214025
//
// Generated by language_helper. Only the values will persist across regenerations.
// Valid value types are limited to `String` or `LanguageCodes`.
//==============================================================================

// Keeps format for the parser
// ignore_for_file: prefer_single_quotes, lines_longer_than_80_chars, file_names

import 'package:language_helper/language_helper.dart';

const zhLanguageData = <String, dynamic>{
  ///===========================================================================
  /// Path: main.dart
  ///===========================================================================
  "@path_main.dart": "",
  "Welcome": '欢迎',
  "Hello": '你好',
  "Goodbye": '再见',
  "Thank you": '谢谢',
  "Please": '请',
  "@{count} items": LanguageConditions(
    param: 'count',
    conditions: {'0': '没有项目', '1': '1 项目', '_': '@{count} 项目'},
  ),
  "Hello, @{name}!": '你好, @{name}!',
  "Settings": '设置',
  "Language": '语言',
  "Theme": '主题',
  "About": '关于',
  "Profile": '个人资料',
  "Logout": '登出',
};
