//==============================================================================
// Generated Date: 2025-11-27T10:46:02.214025
//
// Generated by language_helper. Please do not modify by hand
//==============================================================================

// Keeps format for the parser
// ignore_for_file: always_use_package_imports, lines_longer_than_80_chars

import 'package:language_helper/language_helper.dart';

import 'data/en.dart';
import 'data/vi.dart';
import 'data/zh.dart';

final LanguageData languageData = {
  LanguageCodes.en: enLanguageData,
  LanguageCodes.vi: viLanguageData,
  LanguageCodes.zh: zhLanguageData,
};
